c = complex(3, 1)
d = complex(4, 2)
cinv = complex(3, -1)
dinv = complex(4, -2)

print(-c + d)
print((3 + 1j + 4 - 2j) ** 2)
print(-2j * (1j * c - 5 * d))
print(cinv * (4j + dinv))
print(abs(3 * c + d))
print(c / d)
